# Generated by Django 3.1.2 on 2020-10-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_names', models.TextField()),
                ('output_file_name', models.CharField(max_length=200)),
                ('output_file_path', models.CharField(max_length=250)),
                ('merge_status', models.CharField(max_length=200)),
            ],
        ),
    ]
